[package]
edition = "2021"
name = "sentry-test-server"
version = "0.1.0"

[dependencies]
actix-rt = "2.7"
actix-web = "4"
crossbeam-channel = "0.5"
sentry-types = "0.30"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
